### ISSUE TITLE
CoffeeScript warning message

### ISSUE THREAD

**Issue by rikyperdana** [perak/kitchen-examples#43]
`/Kitchen/accounts/client/client.js:26:26:4: [warning] Operator '==' is not supported in CoffeeScript, use '===' instead
`
It shows warning everytime I try to use coffeescript on a project
Why don't we use 'is' instead of '===' and 'isnt' instead of '!=='

**Comment by perak** [comment]
@rikyperdana js2coffee converter complains because source .js file contains `==` (instead `===`). However, I agree warnings are not welcome. Generated code is little bit outdated, so I need to refactor anyway... but I am not sure how good idea is to continue support for coffee as entire universe is moving to ES6 (and ES7 soon...). What do you think?

**Comment by rikyperdana** [comment]
Can't wait to see kitchen-cli being released ☺
